### ISSUE TITLE
Provide Electron/Cordova wrappers in your example

### ISSUE THREAD

**Issue by lbssousa** [paulvanbladel/quasar-ts#2]
It would be handful if you could provide TS-enabled wrappers for Electon/Cordova in your repository, if needed.

**Comment by paulvanbladel** [comment]
Could you provide  a PR for this?

**Comment by lbssousa** [comment]
I'm closing this issue for now. Investigating a bit further, I've found there's no need to touch electron/cordova wrappers code to make them work with Quasar TypeScript.
