### ISSUE TITLE
Consider pushing your work upstream

### ISSUE THREAD

**Issue by lbssousa** [paulvanbladel/quasar-ts#3]
Upstream project https://github.com/quasarframework/quasar-template-default currently has a [typescript](https://github.com/quasarframework/quasar-template-default/tree/typescript) branch on hold for future plans, but your repo here is much more updated. Have you ever considered submitting a PR with your work to upstream?

**Comment by paulvanbladel** [comment]
Hi 
Wasn't aware of that branch.
Will take a look.
cheers

**Comment by jclijmans** [comment]
Using the work done in this repo, I've created a pull request on the typescript branch of quasar-template-default.

**Comment by paulvanbladel** [comment]
Thanks Jos.
