### ISSUE TITLE
quasar wrap problems

### ISSUE THREAD

**Issue by biancode** [paulvanbladel/quasar-ts#6]
Dear Paul,

thank you for that template, but it crashes after 

quasar wrap electron
cd electron
quasar build darwin

quasar build .... fails

It would be very helpful if the template allows wrapping, please.

kind regards
Klaus

**Comment by paulvanbladel** [comment]
HI Klaus,
Sorry to disappoint you, but I have no electron knowledge whatsoever :(
Maybe try in the quasar forum?

**Comment by biancode** [comment]
OK, thank you!
